version: '3.7'

services:
  # Database Service (Mysql)
  db:
    image: mysql:8
    ports:
      - "3366:3366"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: iodb
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  
  # App backend service
  backend:
    build:
      context: backend # Use an image built from the specified dockerfile in the `backend` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/iodb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123     
    networks:
      - backend
      - frontend

  # Frontend Service 
  frontend:
    build:
      context: frontend # Use an image built from the specified dockerfile in the `frontend` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    