name: Frontend workflow

env:
  node-version: 16.x

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: cd frontend && npm install
      
      - name: Run linter
        run: cd frontend && npm run lint